# .gitlab-ci.yml -- to test some source code build scenarios
# Copyright (C) 2016  Olaf Meeuwissen
#
# License: GPL-3.0+

variables:
  REGISTRY_HUB: "registry.gitlab.com/sane-project/ci-envs"

.build_template: &build_definition
  stage: build
  script:
  - ./configure --enable-silent-rules $CONFIGURE_OPTS
  - make -j2 -k

build:debian-8-full:
  image: $REGISTRY_HUB:debian-8-full
  variables:
    CONFIGURE_OPTS: "--enable-pnm --enable-avahi --enable-libusb_1_0"
  <<: *build_definition

build:debian-8-mini:
  image: $REGISTRY_HUB:debian-8-mini
  <<: *build_definition
